services:
  stratvizzion:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - minha-rede

networks:
  minha-rede:
    external: true
    name: rede-microsservicos

# compose faz com que rode a aplicação
